# -*- coding: utf-8 -*-
"""DecisionMakingAlgorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KVPnmcl8histJqnXZGezsQnIGloZ6Ago
"""

!pip install scikit-learn
!pip install pandas

from sklearn.datasets import load_breast_cancer
import pandas as pd

# Load the Breast Cancer dataset and convert it into a DataFrame
data = load_breast_cancer()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target

# Explore the dataset
print(df.head())
print(df.info())

from sklearn.model_selection import train_test_split

# Handle missing values (example: filling missing values with the median)
df.fillna(df.median(), inplace=True)

# Split the data into features and labels
X = df.drop('target', axis=1)
y = df['target']

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.tree import DecisionTreeClassifier

# Train the decision tree model
tree = DecisionTreeClassifier()
tree.fit(X_train, y_train)

# Make predictions on the test data
y_pred = tree.predict(X_test)

from sklearn.metrics import accuracy_score

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Decision Tree Accuracy: {accuracy * 100:.2f}%")

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

# Plot the decision tree
plt.figure(figsize=(12,8))
plot_tree(tree, filled=True, feature_names=X.columns, class_names=['Class 1', 'Class 2'])
plt.show()